language: android
android:
  components:
  - platform-tools
  - build-tools-27.0.1
  - android-27
  
  - extra-google-m2repository
  - extra-android-m2repository
script:
  - ./gradlew build
before_install:
  - chmod +x gradlew
branches:
  only:
    - master